{{- if .Values.collector.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    app.kubernetes.io/name: collector
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8070
      protocol: TCP
      targetPort: 8070
  selector:
    app.kubernetes.io/name: collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: collector
      app.kubernetes.io/name: collector
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: collector
        app.kubernetes.io/type: collector
        app.kubernetes.io/name: collector
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      containers:
        - name: collector
          image: {{ .Values.collector.image }}
          imagePullPolicy: Always
          env:
            - name: COLLECTOR_ADDR
              value: ":8070"
            - name: COLLECTOR_DIR_PATH
              value: /opt/collector
          command: [ "collector" ]
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "0.5"
              memory: 2Gi
          volumeMounts:
            - mountPath: /opt/collector
              name: collector
          readinessProbe:
            tcpSocket:
              port: 8070
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8070
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: collector
          emptyDir: {}
---
{{- end }}
