---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-scripts
data:
  {{- range $path, $_ := .Files.Glob "scripts/*.sh" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keys
data:
  {{- range $path, $_ := .Files.Glob "configs/keys.json" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4}}
  {{- end }}
---