# API for interacting with the charts for devnet
# TODO: need a way to create state reaching jobs, those will run user bash scripts
# after the chain has been initialized, get the chain to a state and then complete
defaultChains:
  osmosis:
    image: ghcr.io/cosmology-tech/starship/osmosis:v15.1.2-wasmvm1.1.2
    home: /root/.osmosisd
    binary: osmosisd
    prefix: osmo
    denom: uosmo
    coins: 100000000000000uosmo,100000000000000uion
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/osmosis-labs/osmosis
  juno:
    image: ghcr.io/cosmology-tech/starship/juno:v15.0.0
    home: /root/.juno
    binary: junod
    prefix: juno
    denom: ujuno
    coins: 100000000000000ujuno
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/CosmosContracts/juno
  wasmd:
    image: anmol1696/wasmd:latest
    home: /root/.wasmd
    binary: wasmd
    prefix: wasm
    denom: stake
    coins: 100000000000000ucosm,100000000000000stake
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/CosmWasm/wasmd
  cosmos:
    image: ghcr.io/cosmology-tech/starship/gaia:v9.1.1
    home: /root/.gaia
    binary: gaiad
    prefix: cosmos
    denom: uatom
    coins: 100000000000000stake,100000000000000uatom
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmos/gaia
  simapp:
    image: ghcr.io/cosmology-tech/starship/simapp:v0.47.3
    home: /root/.simapp
    binary: simd
    prefix: cosmos
    denom: stake
    coins: 100000000000000stake
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmos/cosmos-sdk/tree/main/simapp
  persistencecore:
    image: anmol1696/persistencecore:latest
    home: /root/.persistenceCore
    binary: persistenceCore
    prefix: persistence
    denom: uxprt
    coins: 100000000000000uxprt
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/persistenceOne/persistenceCore
  stride:
    image: ghcr.io/cosmology-tech/starship/stride:v9.2.1
    home: /root/.stride
    binary: strided
    prefix: stride
    denom: ustrd
    coins: 100000000000000ustrd
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/Stride-Labs/stride
  injective:
    image: ghcr.io/cosmology-tech/starship/injective:v1.11-1685225746
    home: /root/.injectived
    binary: injectived
    prefix: inj
    denom: inj
    coins: 100000000000000inj
    hdPath: m/44'/60'/0'/0/0
    coinType: 60
    repo: https://github.com/InjectiveLabs/injective-chain-releases
  ics:
    image: ghcr.io/cosmology-tech/starship/ics:v0.1.0
    home: /root/.ics
    binary: interchain-security-pd
    prefix: cosmos
    denom: uatom
    coins: 100000000000000stake,100000000000000uatom
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmos/interchain-security
  cronos:
    image: ghcr.io/cosmology-tech/starship/cronos:v1.0.4
    home: /root/.cronos
    binary: cronosd
    prefix: crc
    denom: basecro
    coins: 100000000000000basecro
    hdPath: m/44'/60'/0'/0/0
    coinType: 60
    repo: https://github.com/crypto-org-chain/cronos
  cryptoorgchain:
    image: ghcr.io/cosmology-tech/starship/cryptoorgchain:v4.1.2
    home: /root/.cryptoorgchain
    binary: chain-maind
    prefix: cro
    denom: basecro
    coins: 100000000000000basecro
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/crypto-org-chain/chain-main
  evmos:
    image: ghcr.io/cosmology-tech/starship/evmos:v12.1.5
    home: /root/.evmosd
    binary: evmosd
    prefix: evmos
    denom: aevmos
    coins: 100000000000000aevmos
    hdPath: m/44'/60'/0'/0/0
    coinType: 60
    repo: https://github.com/evmos/evmos
  regen:
    image: ghcr.io/cosmology-tech/starship/regen:v5.0.0
    home: /root/.regen
    binary: regen
    prefix: regen
    denom: uregen
    coins: 100000000000000uregen
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/regen-network/regen-ledger
  quasar:
    image: ghcr.io/cosmology-tech/starship/quasar:v0.1.1
    home: /root/.quasarnode
    binary: quasarnoded
    prefix: quasar
    denom: uqsr
    coins: 100000000000000uqsr
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/quasar-finance/quasar-preview
  quicksilver:
    image: ghcr.io/cosmology-tech/starship/quicksilver:v0.6.6
    home: /root/.quicksilverd
    binary: quicksilverd
    prefix: quick
    denom: uqck
    coins: 100000000000000uqck
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/ingenuity-build/quicksilver
  sei:
    image: ghcr.io/cosmology-tech/starship/sei:2.0.46beta
    home: /root/.seid
    binary: seid
    prefix: sei
    denom: usei
    coins: 100000000000000usei
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/sei-protocol/sei-chain
  sommelier:
    image: ghcr.io/cosmology-tech/starship/sommelier:v6.0.0
    home: /root/.sommelier
    binary: sommelier
    prefix: somm
    denom: usomm
    coins: 100000000000000usomm
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/PeggyJV/sommelier
  stargaze:
    image: ghcr.io/cosmology-tech/starship/stargaze:v10.0.1
    home: /root/.starsd
    binary: starsd
    prefix: stars
    denom: ustars
    coins: 100000000000000ustars
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/public-awesome/stargaze
  umee:
    image: ghcr.io/cosmology-tech/starship/umee:v3.1.0
    home: /root/.umee
    binary: umeed
    prefix: umee
    denom: uumee
    coins: 100000000000000uumee
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/umee-network/umee
  cheqd:
    image: ghcr.io/cosmology-tech/starship/cheqd:v1.4.4
    home: /root/.cheqdnode
    binary: cheqd-noded
    prefix: cheqd
    denom: ncheq
    coins: 100000000000000ncheq
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cheqd/cheqd-node
  neutron:
    image: ghcr.io/cosmology-tech/starship/neutron:v1.0.4
    home: /root/.neutrond
    binary: neutrond
    prefix: neutron
    denom: untrn
    coins: 100000000000000untrn
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/neutron-org/neutron
  eth:
    storageClassName: hostpath
    genesisStateUrl: https://github.com/eth-clients/merge-testnets/blob/main/sepolia/genesis.ssz
    joinNetwork: false
    prysmCtl:
      image: gcr.io/prysmaticlabs/prysm/cmd/prysmctl
      command: ["/app/cmd/prysmctl/prysmctl"]
      args:
        - testnet
        - generate-genesis
        - --num-validators=36
        - --output-ssz=/ethereum/consensus/genesis.ssz
        - --chain-config-file=/etc/config/config.yml
    geth:
      image: ethereum/client-go:v1.12.0
      args:
        - --nodiscover
        - --http
        - --http.api=eth,net,web3,debug
        - --http.addr=0.0.0.0
        - --http.vhosts=*
        - --authrpc.addr=0.0.0.0
        - --authrpc.jwtsecret=/etc/secrets/jwt.hex
        - --datadir=/ethereum/execution
        - --allow-insecure-unlock
        - --unlock=0x123463a4B065722E99115D6c222f267d9cABb524
        - --password=/dev/null
        - --syncmode=full
        - --mine
        - --miner.etherbase=0x123463a4b065722e99115d6c222f267d9cabb524
        - --networkid=32382
    beaconChain:
      image: gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.7
      command: ["/app/cmd/beacon-chain/beacon-chain"]
      args:
        - --datadir=/ethereum/consensus/beacon
        - --min-sync-peers=0
        - --genesis-state=/ethereum/consensus/genesis.ssz
        - --bootstrap-node=
        - --chain-config-file=/etc/config/config.yml
        - --config-file=/etc/config/config.yml
        - --chain-id=32382
        - --rpc-host=0.0.0.0
        - --contract-deployment-block=0
        - --grpc-gateway-host=0.0.0.0
        - --execution-endpoint=http://localhost:8551
        - --accept-terms-of-use
        - --jwt-secret=/etc/secrets/jwt.hex
        - --contract-deployment-block=0
        - --suggested-fee-recipient=0x123463a4B065722E99115D6c222f267d9cABb524
    validator:
      enabled: false
      image: gcr.io/prysmaticlabs/prysm/validator:v4.0.7
      command: ["/app/cmd/validator/validator"]
      args:
        - --accept-terms-of-use
        - --beacon-rpc-provider=localhost:4000
        - --datadir=/ethereum/consensus/validator
        - --interop-num-validators=36
        - --interop-start-index=0
        - --force-clear-db
        - --chain-config-file=/etc/config/config.yml
        - --config-file=/etc/config/config.yml
        - --suggested-fee-recipient=0x0C46c2cAFE097b4f7e1BB868B89e5697eE65f934
    contracts: []

defaultRelayers:
  ts-relayer:
    image: ghcr.io/cosmology-tech/starship/ts-relayer:0.9.0
  hermes:
    image: ghcr.io/cosmology-tech/starship/hermes:1.5.1
    config:
      global:
        log_level: "info"
      mode:
        clients:
          enabled: true
          refresh: true
          misbehaviour: true
        connections:
          enabled: true
        channels:
          enabled: true
        packets:
          enabled: true
          clear_interval: 100
          clear_on_start: true
          tx_confirmation: true
      rest:
        enabled: true
        host: "127.0.0.1"
        port: 3000
      telemetry:
        enabled: true
        host: "127.0.0.1"
        port: 3001
  go-relayer:
    image: anmol1696/go-relayer:v2.4.1 # todo: change this to ghcr.io image

defaultScripts:
  createGenesis:
    name: create-genesis.sh
    file: scripts/create-genesis.sh
  updateGenesis:
    name: update-genesis.sh
    file: scripts/update-genesis.sh
  updateConfig:
    name: update-config.sh
    file: scripts/update-config.sh
  createValidator:
    name: create-validator.sh
    file: scripts/create-validator.sh
  transferTokens:
    name: transfer-tokens.sh
    file: scripts/transfer-tokens.sh
  buildChain:
    name: build-chain.sh
    file: scripts/build-chain.sh
