{{- range $relayer := .Values.relayers }}
{{- if eq $relayer.type "icq" }}
{{ $defaultRelayer := get $.Values.defaultRelayers $relayer.type }}
{{ $initParams := dict "chains" $relayer.chains "port" $.Values.exposer.ports.rest "context" $ }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $relayer.type }}-{{ $relayer.name }}
spec:
  serviceName: {{ $relayer.type }}-{{ $relayer.name }}
  replicas: {{ $relayer.replicas }}
  podManagementPolicy: "Parallel"
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: relayer
      app.kubernetes.io/type: {{ $relayer.type }}
      app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: relayer
        app.kubernetes.io/type: {{ $relayer.type }}
        app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      initContainers:
        {{/* Waits for all upstream chains before starting relayer, vai init containers */}}
        {{- include "devnet.init.wait" $initParams | indent 8 }}
        - name: init-relayer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: RELAYER_DIR
              value: /root/.icq
          command:
            - bash
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              mkdir -p $RELAYER_DIR
              cp /configs/config.yaml $RELAYER_DIR/config.yaml

              MNEMONIC=$(jq -r ".relayers[$RLY_INDEX].mnemonic" $KEYS_CONFIG)
              echo $MNEMONIC

              {{- range $i, $chain := $relayer.chains }}
              {{- range $fullchain := $.Values.chains }}
              {{- if eq $fullchain.name $chain }}
              echo "Creating key for {{ $chain }}..."
              interchain-queries keys restore {{ $chain }}-key "$MNEMONIC" --chain {{ $chain }}
              {{- end }}
              {{- end }}
              {{- end }}
          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /configs
              name: relayer-config
            - mountPath: /keys
              name: keys
          resources:
{{ toYaml $.Values.resources.init | indent 12 }}
      containers:
        - name: relayer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: RELAYER_DIR
              value: /root/.icq
          command:
            - bash
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              interchain-queries run
          resources: {{- include "devnet.node.resources" $relayer | trim | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /configs
              name: relayer-config
      volumes:
        - name: relayer
          emptyDir: { }
        - name: relayer-config
          configMap:
            name: "{{ $relayer.type }}-{{ $relayer.name }}"
        - name: keys
          configMap:
            name: keys
---
{{- end }}
{{- end }}
