chains:
  - name: osmosis
    base: ghcr.io/strangelove-ventures/heighliner/osmosis
    tags:
      - v25.0.2
      - v25.0.0
      - v24.0.3
      - v23.0.0
  - name: gaia
    base: ghcr.io/strangelove-ventures/heighliner/gaia
    tags:
      - v19.2.0
      - v19.1.0
      - v18.1.0
      - v18.0.0
  - name: stride
    base: ghcr.io/strangelove-ventures/heighliner/stride
    tags:
      - v16.0.0
      - v15.0.0
  - name: injective
    base: public.ecr.aws/l9h3g6c6/injective-core
    file: Dockerfile.injective
    tags:
      - v1.12.1
  - name: ics
    base: ghcr.io/strangelove-ventures/heighliner/ics
    tags:
      - v2.0.0-rc1
      - v1.2.0-multiden
      - v2.0.0-rc0
  - name: cronos
    base: ghcr.io/strangelove-ventures/heighliner/cronos
    tags:
      - v1.0.9
      - v1.0.8
  - name: cryptoorgchain
    base: ghcr.io/strangelove-ventures/heighliner/cryptoorgchain
    tags:
      - v4.1.2-croeseid
      - v4.1.2
  - name: evmos
    base: ghcr.io/strangelove-ventures/heighliner/evmos
    tags:
      - v14.0.0-rc4
      - v13.0.2
      - v13.0.1
  - name: juno
    base: ghcr.io/strangelove-ventures/heighliner/juno
    tags:
      - v18.0.0
      - v17.1.1
      - v17.1.0
  - name: persistence
    base: ghcr.io/strangelove-ventures/heighliner/persistence
    tags:
      - v0.2.3
      - v0.2.2
      - v0.1.2
  - name: regen
    base: ghcr.io/strangelove-ventures/heighliner/regen
    tags:
      - v5.1.2
      - v5.1.1
      - v5.1.0
  - name: quasar
    base: ghcr.io/strangelove-ventures/heighliner/quasar
    tags:
      - v0.1.1
      - v0.1.0
  - name: quicksilver
    base: ghcr.io/strangelove-ventures/heighliner/quicksilver
    tags:
      - v0.6.6
  - name: sei
    base: ghcr.io/strangelove-ventures/heighliner/sei
    tags:
      - 2.0.46beta
      - 2.0.45beta
  - name: sommelier
    base: ghcr.io/strangelove-ventures/heighliner/sommelier
    tags:
      - v6.0.0
      - v5.0.0
  - name: stargaze
    base: ghcr.io/strangelove-ventures/heighliner/stargaze
    tags:
      - v10.0.1
      - v10.0.0
  - name: tendermint
    base: ghcr.io/strangelove-ventures/heighliner/tendermint
    tags:
      - v0.37.0-rc2
      - v0.34.24
  - name: umee
    base: ghcr.io/strangelove-ventures/heighliner/umee
    tags:
      - v3.1.0
      - v3.0.3
  - name: wasmd
    base: ghcr.io/strangelove-ventures/heighliner/wasmd
    tags:
      - v0.0.1
  - name: simapp
    base: ghcr.io/strangelove-ventures/heighliner/sim
    tags:
      - v0.47.3
      - v0.50.0-alpha.0
  - name: cheqd
    base: ghcr.io/strangelove-ventures/heighliner/cheqd
    tags:
      - v1.4.4
  - name: neutron
    base: golang:1.21-bullseye
    file: Dockerfile.neutron
    tags:
      - v3.0.6
      - v3.0.5
  - name: union
    base: ghcr.io/unionlabs/uniond
    file: Dockerfile.union
    tags:
      - v0.13.1
      - v0.13.0
      - v0.12.0
  - name: dymension
    base: ghcr.io/strangelove-ventures/heighliner/dymension
    tags:
      - v3.1.0
      - v3.0.0
  - name: kujira
    base: ghcr.io/strangelove-ventures/heighliner/kujira
    tags:
      - v1.1.0
      - v1.0.2
      - v0.9.3
  - name: noble
    base: ghcr.io/strangelove-ventures/heighliner/noble
    tags:
      - v8.0.3
      - v7.0.0
  - name: ethereum/client-go
    base: ethereum/client-go
    file: Dockerfile.base
    tags:
      - latest
      - stable
      - v1.14.12
      - v1.14.11
  - name: prysm-beacon-chain
    base: gcr.io/prysmaticlabs/prysm/beacon-chain
    file: Dockerfile.eth-beacon
    tags:
      - stable
      - v5.2.0
  - name: prysm/validator
    base: gcr.io/prysmaticlabs/prysm/validator
    file: Dockerfile.eth-validator
    tags:
      - stable
      - v5.2.0
  - name: prysm/cmd/prysmctl
    base: gcr.io/prysmaticlabs/prysm/cmd/prysmctl
    file: Dockerfile.eth-prysmctl
    tags:
      - stable
      - v5.2.0
