chains:
  - name: gaia-4
    type: cosmos
    numValidators: 3
    ports:
      rpc: 26653
      rest: 1313
  - name: core-1
    type: persistencecore
    numValidators: 4
    upgrade:
      enabled: true
      type: build
      genesis: v4.0.0
      upgrades:
        - name: v5
          version: v5.0.0-rc1
    ports:
      rpc: 26657
      rest: 1317

relayers:
  - name: persistence-gaia
    type: ts-relayer
    replicas: 1
    chains:
      - gaia-4
      - core-1
