{{- range $chain := .Values.chains }}
{{- if eq $chain.type "virtual" }}
{{- if eq $chain.subtype "eth" }}

apiVersion: v1
kind: Service
metadata:
  name: prysm
  labels:
    app: prysm
spec:
  type: NodePort
  selector:
    app: prysm
  ports:
    - name: beacon-api
      protocol: TCP
      port: 3500
      targetPort: 3500
    - name: geth-http
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: geth-authrpc
      protocol: TCP
      port: 8551
      targetPort: 8551

{{- end }}
{{- end }}
{{- end }}