chains:
  - name: simapp
    type: simapp
    image: ghcr.io/strangelove-ventures/heighliner/simapp:v0.47.3
    numValidators: 2
    ports:
      rest: 1317
      rpc: 26657
    faucet:
      image: ghcr.io/cosmology-tech/starship/cosmjs-faucet:v0.31.0-alpha.2
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "2Gi"

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080
