name: starship
version: v0.2.3

chains:
  - id: osmosis-1
    name: osmosis
    image: pyramation/osmosis:v16.1.0
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007

  - id: cosmos-2
    name: cosmos
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

relayers:
  - name: osmos-cosmos
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - cosmos-2

# explorer:
#   enabled: true
#   ports:
#     rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
